version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=v1qjKkHXq1chKPPlrFqFiMQk
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: sqlite
    volumes:
      - ./wanikani.db:/var/lib/sqlite/wanikani.db

